name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o SenderExe Sender/SenderCheck.cpp

    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o ReceiverExe Receiver/ReceiverCheck.cpp
 
    - name: static analysis
      run: cppcheck --suppress=missingIncludeSystem --check-config --error-exitcode=1 -iReceiver/ReceiverCheck.cpp -iSender/SenderCheck.cpp -iReceiver/ReceiverTest.cpp .
      
    - name: run
      run: ./ReceiverExe
     
    - name: coverage report Sender

      run: gcov -r Sender/SenderCheck.cpp

    - name: coverage report Receiver

      run: gcov -r Receiver/ReceiverCheck.cpp
