name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o SenderExe Sender/SenderCheck.cpp
      
    - name: run
      run: ./SenderExe

    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o ReceiverExe Receiver/ReceiverCheck.cpp
    
    - name: run
      run: ./SenderExe|./ReceiverExe
 
    - name: static analysis
      run: cppcheck --enable=all --check-config --error-exitcode=1 .
     
    - name: coverage report Sender

      run: gcov -b -c SenderCheck.cpp

    - name: coverage report Receiver

      run: gcov -b -c ReceiverTest.cpp
